// Generated by Trae Work
// Cloudflare Pages Function: Handle inquiry form submissions

export async function onRequestPost({ request, env }) {
  // CORS headers
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Content-Type': 'application/json'
  };

  if (request.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const formData = await request.formData();
    const name = formData.get('name');
    const country = formData.get('country');
    const email = formData.get('email');
    const phone = formData.get('phone');
    const productType = formData.get('productType');
    const quantity = formData.get('quantity');
    const message = formData.get('message');

    // Validate required fields: name, country, email
    if (!name || name.trim() === '') {
      return new Response(
        JSON.stringify({ success: false, error: 'Name is required' }),
        { status: 400, headers: corsHeaders }
      );
    }
    if (!country || country.trim() === '') {
      return new Response(
        JSON.stringify({ success: false, error: 'Country is required' }),
        { status: 400, headers: corsHeaders }
      );
    }
    if (!email || email.trim() === '') {
      return new Response(
        JSON.stringify({ success: false, error: 'Email is required' }),
        { status: 400, headers: corsHeaders }
      );
    }

    // Insert into D1 database
    await env.DB.prepare(
      `INSERT INTO inquiries (
        name, country, email, phone, product_type, quantity, message,
        ip_address, user_agent, created_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))`
    ).bind(
      name.trim(),
      country.trim(),
      email.trim(),
      phone || null,
      productType || null,
      quantity || null,
      message || null,
      request.headers.get('CF-Connecting-IP') || '',
      request.headers.get('User-Agent') || ''
    ).run();

    return new Response(
      JSON.stringify({ success: true, message: 'Thank you! We will contact you soon.' }),
      { status: 200, headers: corsHeaders }
    );

  } catch (err) {
    return new Response(
      JSON.stringify({ success: false, error: 'Submission failed: ' + err.message }),
      { status: 500, headers: corsHeaders }
    );
  }
}

