// Generated by Trae Work
// Cloudflare Pages Function: Handle inquiry form submissions

export async function onRequestPost({ request, env }) {
  // CORS headers
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Content-Type': 'application/json'
  };

  if (request.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const data = await request.json();
    const { name, country, phone, email, whatsapp, product, quantity, message } = data;

    // Validate required field
    if (!name || name.trim() === '') {
      return new Response(
        JSON.stringify({ success: false, error: '称呼不能为空' }),
        { status: 400, headers: corsHeaders }
      );
    }

    // Insert into D1 database
    await env.DB.prepare(
      `INSERT INTO inquiries (
        name, country, phone, email, whatsapp, product, quantity, message, 
        ip_address, user_agent, created_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))`
    ).bind(
      name.trim(),
      country || null,
      phone || null,
      email || null,
      whatsapp || null,
      product || null,
      quantity || null,
      message || null,
      request.headers.get('CF-Connecting-IP') || '',
      request.headers.get('User-Agent') || ''
    ).run();

    return new Response(
      JSON.stringify({ success: true, message: '提交成功，我们将尽快与您联系！' }),
      { status: 200, headers: corsHeaders }
    );

  } catch (err) {
    return new Response(
      JSON.stringify({ success: false, error: '提交失败：' + err.message }),
      { status: 500, headers: corsHeaders }
    );
  }
}

export async function onRequestGet({ env }) {
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Content-Type': 'application/json'
  };

  try {
    const { results } = await env.DB.prepare(
      `SELECT id, name, country, phone, email, whatsapp, product, quantity, message, created_at 
       FROM inquiries ORDER BY created_at DESC LIMIT 100`
    ).all();

    return new Response(JSON.stringify(results), { headers: corsHeaders });
  } catch (err) {
    return new Response(
      JSON.stringify({ error: err.message }),
      { status: 500, headers: corsHeaders }
    );
  }
}
